apiVersion: v1
kind: Service
metadata:
  namespace: cincinnati-quality-experiments
  name: cincinnati-monitor-svc
spec:
  selector:
    app: cincinnati-monitor
  ports:
  - protocol: TCP
    port: 23456
    targetPort: 23456